# fly.toml app configuration file for summary-bot-avada

app = 'summary-bot-avada'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'
  TZ = 'Asia/Ho_Chi_Minh'

[[mounts]]
  source = 'bot_data'
  destination = '/app/data'

[deploy]
  strategy = 'immediate'

[processes]
  app = 'node dist/index.js'

[[services]]
  internal_port = 8080
  protocol = 'tcp'
  processes = ['app']
  auto_stop_machines = 'off'
  auto_start_machines = false

  [[services.ports]]
    port = 8080

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
